apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
{{- if eq .Values.type "Deployment"}}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      name: {{ template "fullname" . }}
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
        app: {{ .Chart.Name }}
      annotations:
        prometheus.io/kube-latency: "true"
        prometheus.io/port: {{ .Values.service.internalPort | quote }}
    spec:
      serviceAccount: reader-{{ .Release.Name }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /kube-latency
        - -service-name
        - {{ template "fullname" . }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
          - name: KUBE_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
        resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
